PACKAGE COM.PROYECTOS.BOOKGESTION.DTO.AUTOR_DTO;

IMPORT JAVA.TIME.LOCALDATE;

PUBLIC RECORD AUTORRESPONSEDTO(

    PRIVATE FINAL LONG ID;
PRIVATE FINAL STRING NOMBRE;
PRIVATE FINAL STRING BIOGRAFIA;
PRIVATE FINAL LOCALDATE FECHANACIMIENTO;
PRIVATE FINAL STRING URLFOTO;

) {

}
